### PR TITLE
fix #78

### LINKED ISSUE #78: Why isnt Op class Op op obj origObj impl | op obj origObj -> impl?
I am trying to build a within function, which take a window, a IO (), inject begin window, end window around the IO ().

However, I need to juggle the type so that the result of begin and end need to be returned, or ambiguous type will ensure.

Can we add a FunDep to avoid problem like this?

### PR DESCRIPTION
**Pull request by MarisaKirisame**

### CODE REVIEW

**Comment by deech** [comment]
Hope you don't mind but I issued a commit to your PR that moves `within` into the `Group` hierarchy. This way all `Group` widgets including `Table` and `Tab` will be able to use it and it also allows the opportunity for a 3rd party non-`Group` widget to have a `within` method that does something different.

If you don't want my commit message in there, I have no problem if you want to squash it out of existence. :)

**Comment by MarisaKirisame** [comment]
Look good to me! Thanks :)

**Comment by MarisaKirisame** [comment]
@sboosali I guess so... However I wont be able to code for today, busy with class... I can do it 1~2 days later (or you can step in).

**Comment by deech** [comment]
@sboosali Good point. I can do that.

**Pull request merged**
