### PR TITLE
fix #81, #82. WIP.

### LINKED ISSUE #81: type of windows API should not be IO but should be MonadIO
So I am building a reflex wrapper for fltkhs at https://github.com/MarisaKirisame/reflex-fltk. I had made a special wrapper of newtype FLTK m a = FLTK { unFLTK :: m a } to denote that something is a fltk application, and FL.run will be call automatically.

So far, so good, but if I want to use setXXX, newButton, I have to liftIO everywhere.

Even worse, I cannot replace my implementation of within (which is on FLTK m) with the newly-added within (which is on IO).

I can redefine every function to have impl on FLTK, but I guess a more rational approach is to extend them to generic MonadIO here.

### PR DESCRIPTION
**Pull request by MarisaKirisame**

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
> Also is there any way to not use exceptions? It brings in template-haskell directly and via transformers-compat. One of the goals of this project is to have an absolute minimum of dependencies.

Yes. We can make our own monadmask typeclass, and in other place people can declare instance MonadMask m => OurMonadMask m.

In fltkhs we also have a OurMonadMask IO to run our code.

**Comment by deech** [comment]
You're putting in a lot of work! Thanks!

Before we go further can we talk what advantages `MonadIO` will have over the present situation? From the issue it sounds like you don't want to write `liftIO` all the time. Is there anything else?

**Comment by MarisaKirisame** [comment]
No. It just sucks for my reflex-fltk to call liftIO for virtually everyline.

**Comment by deech** [comment]
I must be missing something really obvious because I forked your repo and was able to remove `liftIO $` from every line in the [`double-buffer` demo](https://github.com/deech/reflex-fltk/blob/master/demo/double_buffer/DoubleBuffer.hs#L53). 

I get that in the future you'll want to pass some of those widgets in to the `Reflex` monad but a lot of the setup (color, font etc.) can be done in `liftIO $ do ...` block.

I also get that `liftIO` is not ideal and `MonadIO` does have some advantages with testing but you lose type inference (which is currently pretty decent), add complexity to the type signatures and take on a dependency.

Not only that all the `fluid` file generation mechanism will have to be changed as well. I also have a sinking suspicion that it won't do good things for compile times.

I really appreciate your contributions and enthusiasm but I'd really like to see a concrete example of a case where you do need `liftIO` on every line.

**Comment by MarisaKirisame** [comment]
Yes, because double-buffer havent use anything from reflex. The only demo that use reflex right now is counter, which need two liftIO and one custom within (since within work only on IO).

And the biggest problem come with having to rewrite within (or any other polymorphic function that turned into IO), since it cant be done with syntax sugar.

Your point is valid, and I think one option is to have xxxM for lifted version and keep xxx.

**Pull request closed without merging**
